services:

  db:
    image: mysql:8.4
    container_name: it-service-desk-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: it-service-desk-web
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES_MINUTES: ${JWT_EXPIRES_MINUTES:-15}
      JWT_COOKIE_SECURE: ${JWT_COOKIE_SECURE:-0}

      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

    ports:
      - "5000:5000"

    volumes:
      - uploads_data:/app/uploads

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  mysql_data:
  uploads_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: