sonar.projectKey=IT-Service-Desk
sonar.projectName=IT Service Desk
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/venv/**,**/__pycache__/**,**/.pytest_cache/**,**/uploads/**,**/.git/**
sonar.python.coverage.reportPaths=coverage.xml