apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: it-service-desk
spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      containers:
        - name: flask
          image: prabhushriyaans/it_service_desk_flask_app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          env:
            - name: DB_HOST
              value: mysql-service

            - name: DB_PORT
              value: "3306"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_NAME

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET_KEY

            - name: JWT_EXPIRES_MINUTES
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_EXPIRES_MINUTES

            - name: JWT_COOKIE_SECURE
              value: "0"

          volumeMounts:
            - name: flask-uploads
              mountPath: /app/uploads

      volumes:
        - name: flask-uploads
          persistentVolumeClaim:
            claimName: flask-uploads-pvc